apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: nodeapp1
spec:
  containers:
  - name: nodeapp
    image: mohamedadel582/nodeapp:1.0
    
    env:
    - name: PORT
      value: "8000"
    - name: MSG
      value: "Hello this is app 1 pod"

---

apiVersion: v1
kind: Service
metadata:
  name: pod-1-service
spec:
  selector:
    app: nodeapp1
  ports:
    - port: 8000
      targetPort: 8000

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: nodeapp2
spec:
  containers:
  - name: nodeapp
    image: mohamedadel582/nodeapp:1.0
    
    env:
    - name: PORT
      value: "8000"
    - name: MSG
      value: "Hello this is app 2 pod"

---

apiVersion: v1
kind: Service
metadata:
  name: pod-2-service
spec:
  selector:
    app: nodeapp2
  ports:
    - port: 8000
      targetPort: 8000
     

  


  

